pipeline {
    agent any

    environment {
        TOKEN = ''
    }

    stages {
        stage('Frond End Deployment') {
            steps {
                sh '''
                    TOKEN=$(aws eks get-token --cluster-name my-eks-cluster --query "status.token" --output text)
                    aws eks update-kubeconfig --region ap-southeast-1 --name my-eks-cluster
                    kubectl config set-credentials eks-user --token=$TOKEN
                    kubectl config set-context --current --user=eks-user
                    kubectl apply -f frontend.yaml
                    unset TOKEN
                '''
            }
        }
    }
}
